CREATE ROLE analyst WITH LOGIN PASSWORD '12345678';
ALTER ROLE analyst CREATEDB;
GRANT ALL PRIVILEGES ON DATABASE lendingclub TO analyst;
CREATE DATABASE lendingclub;

/* after connet to database lendingclub, create the tables we need */

CREATE TABLE loans(
  	id INT,
		member_id INT,
		loan_amnt FLOAT,
		funded_amnt FLOAT,
		funded_amnt_inv FLOAT,
		term INT,
		int_rate FLOAT,
		installment FLOAT,
		grade VARCHAR(1),
		sub_grade VARCHAR(2),
		emp_title TEXT,
		emp_length INT,
		home_ownership VARCHAR(40),
		annual_inc FLOAT,
		verification_status VARCHAR(40),
		issue_d DATE,
		loan_status TEXT,
		pymnt_plan VARCHAR(1),
		url TEXT,
		description TEXT,
		purpose VARCHAR(40),
		title TEXT,
		zip_code VARCHAR(5),
		addr_state VARCHAR(2),
		dti FLOAT,
		delinq_2yrs INT,
		earliest_cr_line DATE,
		inq_last_6mths INT,
		mths_since_last_delinq INT,
		mths_since_last_record INT,
		open_acc INT,
		pub_rec INT,
		revol_bal FLOAT,
		revol_util FLOAT,
		total_acc INT,
		initial_list_status VARCHAR(1),
		out_prncp FLOAT,
		out_prncp_inv FLOAT,
		total_pymnt FLOAT,
		total_pymnt_inv FLOAT,
		total_rec_prncp FLOAT,
		total_rec_int FLOAT,
		total_rec_late_fee FLOAT,
		recoveries FLOAT,
		collection_recovery_fee FLOAT,
		last_pymnt_d DATE,
		last_pymnt_amnt FLOAT,
		next_pymnt_d DATE,
		last_credit_pull_d DATE,
		collections_12_mths_ex_med INT,
		mths_since_last_major_derog INT,
		policy_code TEXT,
		application_type VARCHAR(40),
		annual_inc_joint FLOAT,
		dti_joint FLOAT,
		verification_status_joint VARCHAR(40),
		acc_now_delinq INT,
		tot_coll_amt FLOAT,
		tot_cur_bal FLOAT,
		open_acc_6m INT,
		open_il_6m INT,
		open_il_12m INT,
		open_il_24m INT,
		mths_since_rcnt_il INT,
		total_bal_il FLOAT,
		il_util FLOAT,
		open_rv_12m INT,
		open_rv_24m INT,
		max_bal_bc FLOAT,
		all_util FLOAT,
		total_rev_hi_lim FLOAT,
		inq_fi INT,
		total_cu_tl INT,
		inq_last_12m INT);